apiVersion: v1
kind: PersistentVolume

metadata:
  name: persistent-volume
  labels:
    name: persistent-volume

spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  hostPath:
    path: /mnt/data
