apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: persistent-volume-claim

spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      name: persistent-volume
